apiVersion: apps/v1
kind: Deployment
metadata:
   name: jupiter-spark
   namespace: data-platform
spec:
   replicas: 1
   selector:
      matchLabels:
         app: spark
   template:
      metadata:
         labels:
            app: spark
      spec:
         containers:
            - name: jupiter-spark-container
              image: sonusukralia/jupyterd:3.5
              imagePullPolicy: IfNotPresent
              ports:
              - containerPort: 8888
              env: 
              - name: JUPYTER_ENABLE_LAB
                value: "yes"
              resources:
                requests:
                  memory: "4Gi"  # Minimum memory requested
                limits:
                  memory: "6Gi"  # Maximum memory allowed
---
apiVersion: v1
kind: Service
metadata:
   name: jupiter-spark-svc
   namespace: data-platform
spec:
   type: NodePort
   selector:
      app: spark
   ports:
      - port: 8888
        targetPort: 8888
        nodePort: 30001
---
apiVersion: v1
kind: Service
metadata:
  name: jupiter-spark-driver-headless
spec:
  clusterIP: None
  selector:
    app: spark
