Install Minio

Reference :- https://min.io/docs/minio/kubernetes/upstream/operations/installation.html

1. kubectl apply -k "github.com/minio/operator?ref=v5.0.15"

2. kubectl get pods -n minio-operator

3. kubectl get all -n minio-operator

4. Retrieve the Operator Console JWT for login

{
kubectl apply -f - <<EOF
apiVersion: v1
kind: Secret
metadata:
  name: console-sa-secret
  namespace: minio-operator
  annotations:
    kubernetes.io/service-account.name: console-sa
type: kubernetes.io/service-account-token
EOF
SA_TOKEN=$(kubectl -n minio-operator  get secret console-sa-secret -o jsonpath="{.data.token}" | base64 --decode)
echo $SA_TOKEN
}

5. kubectl port-forward svc/console -n minio-operator 9090:9090

https://192.168.29.15:9443/login

http://localhost:9090/

SA_TOKEN=$(kubectl -n minio-operator  get secret console-sa-secret -o jsonpath="{.data.token}" | base64 --decode)
echo $SA_TOKEN
