apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: spark-master
  namespace: data-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spark-master
  template:
    metadata:
      labels:
        app: spark-master
    spec:
      containers:
      - name: spark-master
        image: sonusukralia/sparkp:3.5
        imagePullPolicy: Always
        command: ["/opt/spark/bin/spark-class"]
        args: ["org.apache.spark.deploy.master.Master", "--host", "0.0.0.0"]
        ports:
        - containerPort: 7077  # Spark master port
        - containerPort: 8080  # Web UI port
        resources:
          requests:
            memory: "2Gi"
            cpu: "500m"
          limits:
            memory: "4Gi"
            cpu: "1000m"

---

apiVersion: v1
kind: Service
metadata:
  name: spark-master-svc
  namespace: data-platform
spec:
  type: ClusterIP
  selector:
    app: spark-master
  ports:
  - name: spark-master
    port: 7077
    targetPort: 7077
  - name: spark-ui
    port: 8080
    targetPort: 8080

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: spark-worker
  namespace: data-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spark-worker
  template:
    metadata:
      labels:
        app: spark-worker
    spec:
      containers:
      - name: spark-worker
        image: sonusukralia/sparkp:3.5
        imagePullPolicy: Always
        command: ["/opt/spark/bin/spark-class"]
        args: ["org.apache.spark.deploy.worker.Worker", "spark://spark-master-svc:7077"]
        ports:
        - containerPort: 8081  # Web UI port for worker
        resources:
          requests:
            memory: "4Gi"
            cpu: "500m"
          limits:
            memory: "5Gi"
            cpu: "4"
